name: docker build and push to ecr

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: type yes to deploy
        required: true
        default: 'no'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check if deployment is confirmed
        if: ${{ github.event.inputs.confirmation != 'yes' }}
        run: |
          echo "Deployment not confirmed. Exiting."
          exit 1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image locally
        run: |
          docker build -t code-server:latest ./code-server

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: 'code-server:latest'
          format: 'sarif'
          exit-code: 0
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Tag Docker image for ECR
        run: |
          docker tag code-server:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/code-server:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/code-server:latest